parser: unbreak `tests::fail_unclosed`, add more unclosed paren tests
nb. `fail_unclosed_after_list` is currently showing eof in the
wrong place:

---- parser::tests::fail_unclosed_after_list stdout ----
error: unclosed delimiter detected
  |
1 | (add 2 (second 3 4)
  | ^ this delimiter
  |                 ^ reached end of file before finding a match
  |

Not having the subtraction by one fixes this, but causes a panic with
`fail_unclosed`. Further investigation is necessary.